modLoader="nonary"
loaderVersion="[25,)" # don't even know if this is used
issueTrackerURL="https://github.com/phantamanta44/libnine/issues/"

[[mods]]
modId="libnine"
version="${file.jarVersion}"
displayName="libnine"
displayURL="https://github.com/phantamanta44/libnine/"
authors="Phanta"
description='Library for writing Good and Cool mods in Good and Cool languages'
